using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public Transform target;
    
    public float Speed;

    public Vector2 center;
    public Vector2 size;
    
    private float height;
    private float width;

    private void Start()
    {
        DontDestroyOnLoad(this.gameObject);
        height = Camera.main.orthographicSize;
        width = height * Screen.width / Screen.height;
    }

    private void OnDrawGizmos()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireCube(center, size);
    }

    private void LateUpdate()
    {
        //transform.position = new Vector3(transform.position.x, transform.position.y, -10f);
        transform.position = Vector3.Lerp(transform.position, target.position, Time.deltaTime * Speed);

        float lx = size.x * 0.5f - width;
        float clampX = Mathf.Clamp(transform.position.x, - lx + center.x, lx + center.x);

        float ly = size.y * 0.5f - height;
        float clampY = Mathf.Clamp(transform.position.y, - ly + center.y, ly + center.y);

        transform.position = new Vector3(clampX, clampY, -10f);
        
    }
}
